### ISSUE TITLE
Improve unet_simple

### ISSUE THREAD

**Issue by Nelson-Gon** [Nelson-Gon/cytounet#18]
**Description**

I would like to improve the initialization of `unet_simple` especially regarding making it similar to what the original paper proposed. 

**Similar Features**

It is currently implemented in `unet_simple`

**Feature Details**

- [x] Improve upsampling

- [x]  Review Downsampling

**Proposed Implementation**

None yet

Thank you

**Comment by nirolada** [comment]
What did the original paper propose?

**Comment by Nelson-Gon** [comment]
Hi, 

In the original [paper](https://link.springer.com/chapter/10.1007%2F978-3-319-24574-4_28), the authors used 23 convolutional layers. 

I think these may be too many for some datasets and it would be better to provide a way to customize the number of layers in the model to avoid overfitting.

**Comment by nirolada** [comment]
I think you might want to add an argument to the function for the conv depth.
def unet-simple(..., depth=3)
'depth' should range from 1 to 3 (representing the number of conv layers at each stage).
What do you think?

**Comment by Nelson-Gon** [comment]
Yes, this is in line what I had in mind. I was also planning to rewrite the whole `unet` method to move away from manually creating layers. In that case, `unet_simple` would not be needed at all. Instead, one would just define the target depth and this would be automatically built.

**Comment by nirolada** [comment]
I will try to look into it soon. If I manage to build something, I will let you know. No need to assign me for now.

**Comment by nirolada** [comment]
Assign it to me, I'll be finished soon.
