### ISSUE TITLE
Using Custom Dataset

### ISSUE THREAD

**Issue by azibit** [Nelson-Gon/cytounet#5]
Hi,
Thanks very much for this wonderful project. I have a custom dataset formatted in form of the COCO dataset. Any suggestions on how I can plug that into this project?

Looking forward to your wonderful response

**Comment by Nelson-Gon** [comment]
Hi,

I have not(yet) looked at COCO datasets mainly because they're often very large which would make it somewhat hard to test due to storage issues. 

I will however look for a small dataset and use this as an example and/or add a custom method for such datasets. This may take some time though.

**Comment by Nelson-Gon** [comment]
Sorry, won't work on this.
