### ISSUE TITLE
Support XML and CSV based annotations 

### ISSUE THREAD

**Issue by Nelson-Gon** [Nelson-Gon/cytounet#6]

**Comment by nirolada** [comment]
Hi, can you provide a description?

**Comment by Nelson-Gon** [comment]
Hi, 

Sorry that this had no description (I had not set these up at the time). 

The basic idea was that, normally for images annotated manually, researchers include annotations of cells. 

For example, for a CSV file, we could have something like this



filename | file_size | file_attributes | region_count | region_id | region_shape_attributes | region_attributes
-- | -- | -- | -- | -- | -- | --
some_filename.jpg | 1681922 | {} | 1 | 0 | {"name":"ellipse","cx":2684,"cy":1540,"rx":571.132,"ry":565.254,"theta":0.538} | {}

The above is taken from something I was working with recently (Unfortunately do not have the corresponding image anymore). The idea then was that given some features in an image as a CSV or XML or JSON file, we could read these, match them to the image, and use these for training. The output of the model would then be an annotated image that contains labeled bounding boxes and an XML/JSON/CSV of the "regions". 

Hopefully this makes it clearer. I think an image could have made it simpler to explain but failed to find one.

Nelson

**Comment by nirolada** [comment]
I can create a class to read annotations from a file supporting CSV and XML.
I will need example files for both formats though.

**Comment by Nelson-Gon** [comment]
I have added sample CSV [annotations](https://github.com/Nelson-Gon/cytounet/tree/master/examples/BBBC030_v1) for five images of the BBBC030_v1 dataset.  

I think it might be better to use one filetype for example XML/JSON. If a different format is supplied, then perhaps convert this to the accepted format and check that it is of the expected structure. Another issue is understanding just how to make sure users will all have a universal file structure. To make the above annotations, I used [VIA 2.0.10](https://www.robots.ox.ac.uk/~vgg/software/via/) and perhaps users should be aware that this is what is expected?

**Comment by Nelson-Gon** [comment]
@nirolada If you'd like to, we can (also) work on [cellseg](https://github.com/Nelson-Gon/cellseg) which uses `torch` which I think makes it easier to use annotations for training.

**Comment by nirolada** [comment]
> I have added sample CSV [annotations](https://github.com/Nelson-Gon/cytounet/tree/master/examples/BBBC030_v1) for five images of the BBBC030_v1 dataset.
> 
> I think it might be better to use one filetype for example XML/JSON. If a different format is supplied, then perhaps convert this to the accepted format and check that it is of the expected structure. Another issue is understanding just how to make sure users will all have a universal file structure. To make the above annotations, I used [VIA 2.0.10](https://www.robots.ox.ac.uk/~vgg/software/via/) and perhaps users should be aware that this is what is expected?

Of course. The user !must! be aware of the accepted format. Additionally, we need to add a JSON&XML schemas and validators to make sure the program receives valid annotation files.

**Comment by nirolada** [comment]
> @nirolada If you'd like to, we can (also) work on [cellseg](https://github.com/Nelson-Gon/cellseg) which uses `torch` which I think makes it easier to use annotations for training.

It is up to you where we add the feature, I kinda don't get the whole picture as you.

**Comment by Nelson-Gon** [comment]
I think it's fine to add it here since I do not yet have a simple working version of the other project.

**Comment by nirolada** [comment]
Can you open a discussion?

**Comment by Nelson-Gon** [comment]
Discussions are now available, thanks!
